Repository NUTFes/group-manager-2, pull requests merged in 2023-05, with the labels that each got.

#1192 ステージオプションの編集ができない問題を解決する #1187
  user_front/components/RegistInfo/edit/StageOption.vue
Labels: バグ修正, ユーザーページ

#1194 マイページのデザイン修正
  user_front/components/Footer.vue
  user_front/components/Mypage/Button.vue
  user_front/components/Mypage/Card.vue
  user_front/components/Mypage/News.vue
  user_front/pages/mypage/index.vue
Labels: デザイン

#1200 トップページのデザイン修正とレスポンシブ化
  user_front/components/WelcomeDetail.vue
  user_front/locales/en.json
  user_front/locales/ja.json
  user_front/pages/index.vue
Labels: デザイン

#1196 マイページのレスポンシブ対応
  user_front/assets/menu.svg
  user_front/components/Footer.vue
  user_front/components/Header.vue
  user_front/components/Mypage/Button.vue
  user_front/pages/mypage/index.vue
Labels: デザイン

#1229 新規登録時のデザイン修正
  user_front/components/RegistPageButton.vue
  user_front/pages/regist/employees/index.vue
  user_front/pages/regist/food/index.vue
  user_front/pages/regist/group/index.vue
  user_front/pages/regist/item/index.vue
  user_front/pages/regist/place/index.vue
  user_front/pages/regist/power/index.vue
  user_front/pages/regist/purchase/index.vue
  user_front/pages/regist/stage/rain.vue
  user_front/pages/regist/stage/sunny.vue
  user_front/pages/regist/stageOption/index.vue
  user_front/pages/regist/subrep/index.vue
  user_front/pages/regist/user/index.vue
Labels: user_front, デザイン

#1232 cssが崩れて、リロードすると直る問題を修正
  user_front/pages/mypage/edit_user_info/index.vue
  user_front/pages/mypage/password_reset/index.vue
Labels: バグ修正

#1238 物品重複時にエラーが出るようにする
  user_front/pages/regist/item/index.vue
Labels: バグ修正

#1240 物品申請を登録しすぎるとはみ出すバグ修正
  user_front/components/RegistInfo/add/Employee.vue
  user_front/components/RegistInfo/add/Food.vue
  user_front/components/RegistInfo/add/Item.vue
  user_front/components/RegistInfo/add/Power.vue
  user_front/components/RegistInfo/add/Purchase.vue
  user_front/components/RegistInfo/edit/Employee.vue
  user_front/components/RegistInfo/edit/Food.vue
  user_front/components/RegistInfo/edit/Item.vue
  user_front/components/RegistInfo/edit/Place.vue
  user_front/components/RegistInfo/edit/Power.vue
  user_front/components/RegistInfo/edit/Purchase.vue
  user_front/components/RegistInfo/edit/Stage.vue
  user_front/components/RegistInfo/edit/StageOption.vue
  user_front/components/RegistInfo/edit/SubRep.vue
  user_front/pages/regist_info/index.vue
Labels: バグ修正

#1282 会場申請に画像URLを表示
  admin_view/nuxt-project/pages/place_orders/_id.vue
  api/app/models/place_order.rb
Labels: api, admin_view

#1289 PR文とアナウンス文にバリデーションをつける
  user_front/locales/en.json
  user_front/locales/ja.json
  user_front/pages/mypage/edit_announcement/index.vue
  user_front/pages/mypage/publicRelations/index.vue
  user_front/pages/regist/announcement/index.vue
  user_front/pages/regist/publicRelations/index.vue
Labels: 機能追加

#1300 アナウンス文の登録・編集ができない問題の解決
  user_front/pages/mypage/edit_announcement/index.vue
Labels: バグ修正

#1330 副代表申請の編集モーダルで所属が空値でも編集できる
  api/db/fixtures/develop/news.rb
  user_front/components/Mypage/News.vue
  user_front/components/RegistInfo/edit/SubRep.vue
Labels: バグ修正, デザイン

#1334 Passwordリセットのバリデーションを追加
  user_front/pages/mypage/password_reset/index.vue
  user_front/types/mypage/passwordReset.ts
  user_front/utils/validate.ts
Labels: user_front

#1337 参加団体情報のバリデーションを追加
  user_front/pages/mypage/edit_group/index.vue
Labels: バグ修正

#1341 ステージ申請の重複バリデーションを追加
  user_front/pages/regist_info/index.vue
Labels: バグ修正, user_front

#1345 [fix] ステージ申請で雨の場合でも登録できるように
  user_front/components/RegistInfo/add/Stage.vue
Labels: バグ修正, user_front

#1348 [fix] 重複バリデーションを修正
  user_front/pages/regist_info/index.vue
Labels: バグ修正, user_front

#1361 開催日数のシードデータ変更とgradeの教員追加
  api/db/fixtures/develop/grade.rb
  api/db/fixtures/production/fes_year_date.rb
  api/db/fixtures/production/grade.rb
  user_front/pages/regist_info/index.vue
  user_front/utils/list.ts
Labels: バグ修正, 機能追加, user_front

#1364 画像登録をimgurで行うようにする
  admin_view/nuxt-project/components/VerticalTable.vue
  admin_view/nuxt-project/pages/place_orders/_id.vue
  user_front/nuxt.config.ts
  user_front/pages/mypage/publicRelations/index.vue
  user_front/pages/regist/venueMap/index.vue
Labels: 機能追加
